services:
    backend:
        build:
            context: .
        container_name: nestboard-backend-local
        env_file:
            - .env.prod
        ports:
            - "8000:8000"
        depends_on:
            - db
        restart: unless-stopped

    db:
        image: postgres:17
        container_name: nestboard-db-local
        environment:
            POSTGRES_USER: nestboard_user
            POSTGRES_PASSWORD: superpassword
            POSTGRES_DB: nestboard
        ports:
            - "5433:5432"
        volumes:
            - postgres_data_local:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data_local:
