"""Suppression du prix d'un article, seul source de vérité, le prix catalogue produit

Revision ID: 07615a8ba4d1
Revises: 6d04b88005b1
Create Date: 2026-03-16 14:47:06.378689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07615a8ba4d1'
down_revision: Union[str, Sequence[str], None] = '6d04b88005b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
