"""Ajout emplacement mall

Revision ID: 61a72a78e480
Revises: 7437e4f14613
Create Date: 2026-02-27 15:28:27.749304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a72a78e480'
down_revision: Union[str, Sequence[str], None] = '7437e4f14613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malls', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('malls', 'location')
    # ### end Alembic commands ###
