"""Modifications des shoppingListItems pour utilisation des coupons et tri personalisé

Revision ID: 9efb0e0ee824
Revises: c124941adc70
Create Date: 2026-03-05 17:28:48.218623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efb0e0ee824'
down_revision: Union[str, Sequence[str], None] = 'c124941adc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('custom_sort_index', sa.Integer(), nullable=True))
    op.add_column('shopping_list_items', sa.Column('need_coupons', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'need_coupons')
    op.drop_column('shopping_list_items', 'custom_sort_index')
    # ### end Alembic commands ###
