"""Unicité de certain champs

Revision ID: c124941adc70
Revises: 6ae57db129fc
Create Date: 2026-03-03 10:59:39.776450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c124941adc70'
down_revision: Union[str, Sequence[str], None] = '6ae57db129fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index('uq_products_name_category_notnull', 'products', ['name', 'category_id'], unique=True, postgresql_where=sa.text('category_id IS NOT NULL'))
    op.create_index('uq_products_name_category_null', 'products', ['name'], unique=True, postgresql_where=sa.text('category_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_products_name_category_null', table_name='products', postgresql_where=sa.text('category_id IS NULL'))
    op.drop_index('uq_products_name_category_notnull', table_name='products', postgresql_where=sa.text('category_id IS NOT NULL'))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    # ### end Alembic commands ###
