"""Suppression du nom des listes de courses

Revision ID: c13a3aff9788
Revises: 61a72a78e480
Create Date: 2026-02-27 15:47:20.082218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13a3aff9788'
down_revision: Union[str, Sequence[str], None] = '61a72a78e480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_lists_name'), table_name='shopping_lists')
    op.drop_column('shopping_lists', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_shopping_lists_name'), 'shopping_lists', ['name'], unique=False)
    # ### end Alembic commands ###
