"""Système de maison

Revision ID: dc9e309caf5d
Revises: b54aaebe8b13
Create Date: 2026-02-27 11:10:34.352689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9e309caf5d'
down_revision: Union[str, Sequence[str], None] = 'b54aaebe8b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('invitation_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.create_index(op.f('ix_houses_invitation_code'), 'houses', ['invitation_code'], unique=True)
    op.create_index(op.f('ix_houses_name'), 'houses', ['name'], unique=False)
    op.add_column('users', sa.Column('house_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'privileges',
               existing_type=sa.VARCHAR(),
               server_default='user',
               nullable=False)
    op.create_foreign_key(None, 'users', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'privileges',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.drop_column('users', 'house_id')
    op.drop_index(op.f('ix_houses_name'), table_name='houses')
    op.drop_index(op.f('ix_houses_invitation_code'), table_name='houses')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
