"""Added add by user id field

Revision ID: ecad5a5a6357
Revises: 07615a8ba4d1
Create Date: 2026-03-25 10:44:22.431845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecad5a5a6357'
down_revision: Union[str, Sequence[str], None] = '07615a8ba4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_list_items', 'users', ['added_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_list_items', type_='foreignkey')
    op.drop_column('shopping_list_items', 'added_by_user_id')
    # ### end Alembic commands ###
