"""Ajout DB frigo

Revision ID: fe7bfeb5d119
Revises: ecad5a5a6357
Create Date: 2026-04-01 15:57:24.975827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7bfeb5d119'
down_revision: Union[str, Sequence[str], None] = 'ecad5a5a6357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('main', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridges_id'), 'fridges', ['id'], unique=False)
    op.create_index(op.f('ix_fridges_name'), 'fridges', ['name'], unique=False)
    op.create_table('fridge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('fridge_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridges.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_items_id'), 'fridge_items', ['id'], unique=False)
    op.add_column('products', sa.Column('fridge_product', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fridge_product')
    op.drop_index(op.f('ix_fridge_items_id'), table_name='fridge_items')
    op.drop_table('fridge_items')
    op.drop_index(op.f('ix_fridges_name'), table_name='fridges')
    op.drop_index(op.f('ix_fridges_id'), table_name='fridges')
    op.drop_table('fridges')
    # ### end Alembic commands ###
